### ISSUE TITLE
predict.py issue

### ISSUE THREAD

**Issue by rurubaobao** [Reagan1311/DABNet#23]
hello，when I predict the camvid dataset,I have this issue:
Traceback (most recent call last):
  File "C:/Users/lenovo/PycharmProjects/fr/gleason/DABNet-master/predict.py", line 112, in <module>
    test_model(args)
  File "C:/Users/lenovo/PycharmProjects/fr/gleason/DABNet-master/predict.py", line 83, in test_model
    predict(args, testLoader, model)
  File "C:/Users/lenovo/PycharmProjects/fr/gleason/DABNet-master/predict.py", line 25, in predict
    for i, (input, size, name) in enumerate(test_loader):
ValueError: too many values to unpack (expected 3)

**Comment by Reagan1311** [comment]
If you want to predict the Camvid dataset, use the test.py, predict.py is used to output the prediction for official evaluation like Cityscapes dataset
