### ISSUE TITLE
用的cityscapes官网的数据集训练一直报错误

### ISSUE THREAD

**Issue by zhongjiansheng** [Reagan1311/DABNet#34]
Traceback (most recent call last):
  File "train.py", line 314, in <module>
    train_model(args)
  File "train.py", line 217, in train_model
    lossTr, lr = train(args, trainLoader, model, criteria, optimizer, epoch)
  File "train.py", line 81, in train
    loss = criterion(output, labels)
  File "/home/stu/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/stu/user/jszhong/Research/DABNet/utils/loss.py", line 87, in forward
    index = mask_prob.argsort()
RuntimeError: merge_sort: failed to synchronize: device-side assert triggered

**Comment by Reagan1311** [comment]
your label map should be 0\~18, not color map, which is 0~255.
So you should first convert the label map, you can find the relevant code in [cityscapesScripts](https://github.com/mcordts/cityscapesScripts)
