### ISSUE TITLE
Hi, I have got some problems about train.py.

### ISSUE THREAD

**Issue by shiweigao** [Reagan1311/DABNet#37]
I found that the names of the pictures in train_list.txt do not match the cityscapes, like "cologne_000000_000019_gtFine_labelTrainIds.png" and "cologne_000000_000019_gtFine_labelIds.png". After the change, the error is reported as follows:
Traceback (most recent call last):
  File "train.py", line 314, in <module>
    train_model(args)
  File "train.py", line 217, in train_model
    lossTr, lr = train(args, trainLoader, model, criteria, optimizer, epoch)
  File "train.py", line 81, in train
    loss = criterion(output, labels)
  File "/home/uber/anaconda3/envs/DABNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/uber/GraduateWork/2020/DABNet/DABNet-master/utils/loss.py", line 81, in forward
    index = mask_prob.argsort()
  File "/home/uber/anaconda3/envs/DABNet/lib/python3.6/site-packages/torch/tensor.py", line 248, in argsort
    return torch.argsort(self, dim, descending)
  File "/home/uber/anaconda3/envs/DABNet/lib/python3.6/site-packages/torch/functional.py", line 651, in argsort
    return torch.sort(input, -1, descending)[1]
RuntimeError: merge_sort: failed to synchronize: device-side assert triggered

Could I get some help from you?

**Comment by Reagan1311** [comment]
please refer to #34, hope this helps.

**Comment by shiweigao** [comment]
thx！
